version: '3'

services:
  db:
    container_name: post_db
    image: postgres:16.2-alpine3.19 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # volumes:
    #   - go_server:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    # command: >
    #  bash -c "
    #  echo 'Waiting for PostgreSQL to start...' &&
    #  until pg_isready -h localhost -p 5432 -U postgres; do
    #    sleep 1;
    #  done;
    #  psql -U postgres -c 'CREATE DATABASE go_http;'"
  
  server:
    container_name: go_s
    image: go_http:fire
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
    ports:
      - 2000:2000

